print("name saba")
print("nickname yurashvili")
print("age 13")
print("live in georgia")
print("live in qvemo qartli")
print("live in city rustavi")
print("am learning in fourth scool")
print("favorite subject in scool is sport")
print("hobby computer")
print("favorite animal dog")
print("favorite programing language python or gd script")
print("favorite food awaruli 😋 or mawadi 😋 ")
print("favorite sprot football")
print("best friend dato and saba")
print("favorite film probably silace in front ")
print("height = 1,70")
print("favorite tv show moonwarior")
print("favorite music sprinter by central cee")
print("favorite car is porche")
print("favorite academy goa")