name = input("what is you name")
print("you name is" name )
age = input("what is your age   ")
print("your age is" age)
surname = input("surname??")
print("your are "surname)
num1 = input("enter num1")
num2 = input("enter num2")
print(num1 + num2)
